// <auto-generated />
namespace SharpBooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class oauth_google_and_thefacedevil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oauth_google_and_thefacedevil));
        
        string IMigrationMetadata.Id
        {
            get { return "201412030109060_oauth_google_and_thefacedevil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
