// <auto-generated />
namespace SharpBooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BookShelf_To_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookShelf_To_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201412010330132_BookShelf_To_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
