// <auto-generated />
namespace SharpBooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class bookshelf_validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookshelf_validation));
        
        string IMigrationMetadata.Id
        {
            get { return "201412030401142_bookshelf_validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
